### ISSUE TITLE
Support non-ASCII characters in paths

### ISSUE THREAD

**Issue by birjj** [sindresorhus/slash#19]
This project claims that

> [Forward-slash paths can be used in Windows](http://superuser.com/a/176395/6877) as long as they're not extended-length paths and don't contain any non-ascii characters.

However, the linked SuperUser answer does not mention the non-ASCII limitation. The [official documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) also makes no mention of it, instead noting that

> File I/O functions in the Windows API convert "/" to "\\" as part of converting the name to an NT-style name, except when using the "\\\\?\\" prefix as detailed in the following sections.

(this quote [used to be](https://archive.ph/on8B) on the documentation site linked in the SuperUser answer, but has since been moved to the "Maximum File Path Limitation" page)

Is there any documentation or examples to support the non-ASCII limitation in this project? From [my own anecdotal testing](https://github.com/facebook/docusaurus/issues/8124#issuecomment-1255289740) it appears that paths with non-ASCII characters and forward slash path separators *are* supported in Windows and Node.js.

If there is no documentation, could this project be updated to support them? It appears to cause many problems in projects that rely on it, e.g. https://github.com/facebook/docusaurus/issues/8124, https://github.com/gatsbyjs/gatsby/pull/19600, and https://github.com/SAP/ui5-tooling/issues/469, amongst others.

**Comment by Vladisvob** [comment]
Duplicate of #

**Comment by Vladisvob** [comment]
> Tvrdí to tento projekt
> 
> > [Cesty s lomítkem lze použít ve Windows](http://superuser.com/a/176395/6877) , pokud se nejedná o cesty s prodlouženou délkou a neobsahují žádné jiné znaky než ASCII.
> 
> Propojená odpověď SuperUser však nezmiňuje omezení bez ASCII. Oficiální [dokumentace](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) se o tom také nezmiňuje, místo toho to uvádí
> 
> > Funkce I/O souboru v rozhraní Windows API převádějí „/“ na „\“ jako součást převodu názvu na název ve stylu NT, s výjimkou použití předpony „\\?\“, jak je podrobně popsáno v následujících částech.
> 
> (tato citace [bývala](https://archive.ph/on8B) na stránce s dokumentací, na kterou odkazuje odpověď SuperUser, ale od té doby byla přesunuta na stránku „Maximální omezení cesty k souboru“).
> 
> Existuje nějaká dokumentace nebo příklady na podporu omezení ne-ASCII v tomto projektu? Z [mého vlastního neoficiálního testování](https://github.com/facebook/docusaurus/issues/8124#issuecomment-1255289740) se zdá, že cesty s jinými znaky než ASCII a oddělovači cest _jsou_ podporovány ve Windows a Node.js.
> 
> Pokud neexistuje žádná dokumentace, mohl by být tento projekt aktualizován, aby je podpořil? Zdá se, že způsobuje mnoho problémů v projektech, které na něj spoléhají, např. [facebook/docusaurus#8124](https://github.com/facebook/docusaurus/issues/8124) , [gatsbyjs/gatsby#19600](https://github.com/gatsbyjs/gatsby/pull/19600) a [SAP/ui5-tooling#469](https://github.com/SAP/ui5-tooling/issues/469) a další.
