### ISSUE TITLE
Support non-ASCII characters in Commonjs

### ISSUE THREAD

**Issue by leopucci** [sindresorhus/slash#22]
HI. This lib has been updated to type module but electron still does not support modules, so I am not able to use the latest version of this lib. But the fix of non-ascii chars are only in the newest version. 
Any way to get this fixed on the old versions too?
Thanks!

**Comment by sindresorhus** [comment]
I have no plans to backport it. The code is super simple, so I suggest you just copy-paste it.

**Comment by sindresorhus** [comment]
https://stackoverflow.com/a/70895828/64949
