### ISSUE TITLE
Slash doesn't work on filepaths

### ISSUE THREAD

**Issue by IrosTheBeggar** [sindresorhus/slash#4]
I use this library for a project of mine and it's worked great to smooth stuff that has to be synced across windows and linux

I recently wrote a script that uses this on a filepath and noticed it was returning the filepath with the Windows format still in place

**Comment by kevva** [comment]
Some code would be really helpful to make it easier to debug :).

**Comment by IrosTheBeggar** [comment]
Sorry, I just dug in some more and it has to do with the files I'm running have special characters.  Looks like this library returns the input string if that's the case
